# Generated by Django 3.2.11 on 2022-06-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='app',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
