# Generated by Django 3.2.11 on 2022-06-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_image_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningapp',
            name='state',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
